export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const ADD_FROM_MENU = "ADD_FROM_MENU";
export const CLEAR_CART = "CLEAR_CART";